// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiW-o3Fph8bmB31oVZjWlckSwXD9Qh3FY',
    appId: '1:601199941384:web:3915f0e7e80779dfe0febd',
    messagingSenderId: '601199941384',
    projectId: 'moneymove-6916c',
    authDomain: 'moneymove-6916c.firebaseapp.com',
    storageBucket: 'moneymove-6916c.firebasestorage.app',
    measurementId: 'G-YL11B7X9QC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvq7HyM9bvbnck55JB2JHwSVxA9D5wh3M',
    appId: '1:601199941384:android:fcdf9472a5680f0ee0febd',
    messagingSenderId: '601199941384',
    projectId: 'moneymove-6916c',
    storageBucket: 'moneymove-6916c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMBTs8PUNv0Ytszp7xHMtO8xYES_rZRy0',
    appId: '1:601199941384:ios:466f5e461c1ed2bde0febd',
    messagingSenderId: '601199941384',
    projectId: 'moneymove-6916c',
    storageBucket: 'moneymove-6916c.firebasestorage.app',
    androidClientId: '601199941384-v3ojiu5kfvntirr3321io350rioh37m1.apps.googleusercontent.com',
    iosClientId: '601199941384-rhb7bl9i869d0asdqgfinvnrhn5r8v04.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyMove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMBTs8PUNv0Ytszp7xHMtO8xYES_rZRy0',
    appId: '1:601199941384:ios:466f5e461c1ed2bde0febd',
    messagingSenderId: '601199941384',
    projectId: 'moneymove-6916c',
    storageBucket: 'moneymove-6916c.firebasestorage.app',
    androidClientId: '601199941384-v3ojiu5kfvntirr3321io350rioh37m1.apps.googleusercontent.com',
    iosClientId: '601199941384-rhb7bl9i869d0asdqgfinvnrhn5r8v04.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyMove',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiW-o3Fph8bmB31oVZjWlckSwXD9Qh3FY',
    appId: '1:601199941384:web:15c6f39c87530044e0febd',
    messagingSenderId: '601199941384',
    projectId: 'moneymove-6916c',
    authDomain: 'moneymove-6916c.firebaseapp.com',
    storageBucket: 'moneymove-6916c.firebasestorage.app',
    measurementId: 'G-G0T3Y7DBC6',
  );

}